
services:
  postgres:
    image: postgres:16-alpine
    container_name: account-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - account-network

  redis:
    image: redis:7-alpine
    container_name: account-redis
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - account-network


  account_app:
   build: .
   container_name: account-app
   ports:
     - "${SERVER_PORT}:8080"
   environment:
     REDIS_HOST: ${REDIS_HOST}
     REDIS_PORT: ${REDIS_PORT}
     POSTGRES_HOST: ${POSTGRES_HOST}
     POSTGRES_PORT: ${POSTGRES_PORT}
     POSTGRES_DB: ${POSTGRES_DB}
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     TELEMETRY_GRPC_HOST: ${TELEMETRY_GRPC_HOST}
     TELEMETRY_GRPC_PORT: ${TELEMETRY_GRPC_PORT}
   depends_on:
     postgres:
       condition: service_healthy
     redis:
       condition: service_healthy
   networks:
    - account-network



volumes:
  postgres_data:

networks:
  account-network:
    driver: bridge